### ISSUE TITLE
"Automatically keep private github repository up-to-date" does not work (no tailwind.css file created) with prefixClasses enabled

### ISSUE THREAD

**Issue by connecteev** [kiliman/tailwindui-crawler#30]
No css file is created if you have the tw- prefix enabled and use the github action to automatically keep a private github repository up-to-date.

It does build periodically, and the code gets checked into the private git repo, but there is no .css file created, so when you run ``` npx serve```, the pages look broken.

The Main page at http://localhost:5000/ looks ok: 
https://www.webpagescreenshot.info/#v2=QXGpcmiSB

However, the rest of the pages look broken.
Screenshots:
https://www.webpagescreenshot.info/#v2=3S7WF3he-
https://www.webpagescreenshot.info/#v2=xOuZUmwkY

These are the steps I took:
https://github.com/kiliman/tailwindui-crawler#automatically-keep-a-private-github-repository-up-to-date

.env file:
```
OUTPUT=./tailwindui_output
BUILDINDEX=1
HTMLMODE=alpine
TRANSFORMERS=addTailwindCss,prefixSrc,useInter,prefixClasses,convertVue,stripAlpine
VUE_OUTPUT=$OUTPUT/vue
STRIPALPINE_OUTPUT=$OUTPUT/no-alpine
ADDTAILWINDCSS_URL=/tailwind.css
PREFIXCLASSES_PREFIX=tw-

```

```
# .github/workflows/default.yml

name: Update
on:
  push:
  schedule:
    - cron: "*/5 * * * *" # Every 5th minute

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run crawler
        uses: gregbrimble/tailwindui-crawler-action@v1.0.0
        with:
          email: ${{ secrets.TAILWINDUI_EMAIL }}
          password: ${{ secrets.TAILWINDUI_PASSWORD }}
          
```
