### ISSUE TITLE
Update GitHub Action to support new crawler v3

### ISSUE THREAD

**Issue by kiliman** [kiliman/tailwindui-crawler#46]
Make sure the action uses the latest version of the crawler, as v2 will not properly parse the updated Tailwind UI site.

/cc @GregBrimble

**Comment by kiliman** [comment]
That is odd. I just re-ran it (from a clean output folder) and get all the vue components.

NOTE: I did this from a local install. What happens if you run the crawler locally?

![image](https://user-images.githubusercontent.com/47168/114882775-4c13ef80-9dd2-11eb-8d83-76edbd98fb66.png)

**Comment by ademers** [comment]
Was using my existing private repo. Maybe it's best I start over from scratch.

**Comment by heychazza** [comment]
I was also using my existing repo and got same results, will give it a shot with a clean repo later..

**Comment by GregBrimble** [comment]
I'm currently just pulling the latest changes and figuring out what (if any) changes need to be made :) Gimme about 30 mins – 1 hour, and I should have it all working and updated.

**Comment by GregBrimble** [comment]
New v1.1.0 release has been published: https://github.com/marketplace/actions/crawl-tailwind-ui

Just update your workflow files from 

```diff
# ...
      - name: Run crawler
-        uses: gregbrimble/tailwindui-crawler-action@v1.0.0
+        uses: gregbrimble/tailwindui-crawler-action@v1.1.0
        with:
          email: ${{ secrets.TAILWINDUI_EMAIL }}
          password: ${{ secrets.TAILWINDUI_PASSWORD }}
```

That should be all that's required for old repositories with a `master` default branch. If you're using a new repository, or have changed your default branch, you'll need to specify `branch` like so:

```diff
# ...
      - name: Run crawler
        uses: gregbrimble/tailwindui-crawler-action@v1.1.0
        with:
          email: ${{ secrets.TAILWINDUI_EMAIL }}
          password: ${{ secrets.TAILWINDUI_PASSWORD }}
+         branch: main
```          

I'll update this project's README.md in just a couple of minutes.

**Comment by kiliman** [comment]
Hmm... first time trying the Action and I'm seeing the following:

If I choose 'alpine' for languages, I'm saving the preview HTML. However, I'm getting different results when running locally vs running in the action. It's auto-closing tags and stripping HTML entities. Red is local version and green is from action.

I'm not sure why it would return different HTML. Unfortunately the action version is incorrect as the HTML entities are critical. Especially with embedded quotes `&quot;`

![image](https://user-images.githubusercontent.com/47168/114916088-63fb6b80-9df2-11eb-8dbc-2ec299ea5434.png)
![image](https://user-images.githubusercontent.com/47168/114916126-6d84d380-9df2-11eb-9953-9ae846808541.png)
![image](https://user-images.githubusercontent.com/47168/114916190-7fff0d00-9df2-11eb-9020-24a16d246a66.png)
![image](https://user-images.githubusercontent.com/47168/114916372-b63c8c80-9df2-11eb-83a7-ed9a2487d156.png)

**Comment by kiliman** [comment]
I updated the package versions (pushed as v3.1.3) and it now works properly on the GitHub Action.

Thanks for taking care of this!

**Comment by heychazza** [comment]
Morning both,

Had an issue originally which was fixed by creating a new repo (very strange). However I have now tried again, and its only creating the html version..

Using the TailwindUI Crawler.

**.env**
```
LANGUAGES=html,react,vue,alpine # defaults to html
BUILDINDEX=1  # generate index file to view components offline
```

**.github/workflows/default.yml**
```
name: Update
on:
  workflow_dispatch: # On manual trigger
  schedule:
    - cron: "0 0 * * *" # Every day at midnight

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run crawler
        uses: gregbrimble/tailwindui-crawler-action@v1.1.0
        with:
          email: ${{ secrets.TAILWINDUI_EMAIL }}
          password: ${{ secrets.TAILWINDUI_PASSWORD }}
          branch: main
```

![image](https://user-images.githubusercontent.com/47271716/114988193-f56beb80-9e8d-11eb-9d3e-8b067ce4e305.png)


Also, weirdly it's using "root" rather than my own avatar.

cc: @kiliman @GregBrimble 

Thanks a ton to you both for creating both things, been incredibly useful.

**Comment by GregBrimble** [comment]
@heychazza , try also adding `current_branch: main` as well as `branch: main`.

You're seeing html only because that's the crawler default, and it's not picking up the `.env` in the `current_branch` which defaults to `master`.

Sorry, I should have made that clearer.

**Comment by heychazza** [comment]
> @heychazza , try also adding `current_branch: main` as well as `branch: main`.
> 
> You're seeing html only because that's the crawler default, and it's not picking up the `.env` in the `current_branch` which defaults to `master`.
> 
> Sorry, I should have made that clearer.

You're a star! Thank you so much :)

It runs (I ended up just using a new repo aha), however Alpine version is non existent though the others have (html, vue and react).

Maybe more of a issue with the crawler itself rather than the action? Once again, thanks to you both a ton for building these and being fast with responses 👍

**Comment by GregBrimble** [comment]
Do you pin the crawler version with `crawlerref`? I think Alpine support was added as a new release. By default, my Action should be pulling `master`.

Can you reproduce locally with that exact same `.env` file?

**Comment by heychazza** [comment]
Hey buddy,

**.env**
```
LANGUAGES=html,react,vue,alpine # defaults to html
BUILDINDEX=1  # generate index file to view components offline
```

workflow:
```yml
name: Update
on:
  workflow_dispatch: # On manual trigger
  schedule:
    - cron: "0 0 * * *" # Every day at midnight

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run crawler
        uses: gregbrimble/tailwindui-crawler-action@v1.1.0
        with:
          email: ${{ secrets.TAILWINDUI_EMAIL }}
          password: ${{ secrets.TAILWINDUI_PASSWORD }}
          branch: main
          current_branch: main
          actor: heychazza
```

I don't currently use `crawlerref`

**Comment by GregBrimble** [comment]
@heychazza , I can't reproduce. Alpine components get pulled as expected for me. Any chance you can share your repo with me so I can take a look at the Action logs, and whatever else might help us find out why this isn't working for you?

**Comment by heychazza** [comment]
Hey @GregBrimble,

Fixed it by moving `alpine`.. haha..

From..
```
LANGUAGES=html,react,vue.alpine # defaults to html
BUILDINDEX=1  # generate index file to view components offline
```

To..
```
LANGUAGES=alpine,html,react,vue # defaults to html
BUILDINDEX=1  # generate index file to view components offline
```

Not sure if Github caches the .env which is the cause here, or the order mattered.

**Comment by heychazza** [comment]
Ok, so doing that has caused vue to disappear..

```
📝  Writing html simple_centered.html
📝  Writing react simple_centered.jsx
📝  Writing alpine simple_centered.html
```

**Comment by GregBrimble** [comment]
Again, unfortunately can't reproduce. Adding `vue` and `alpine` to `.env` seem to work as expected for me. Can you share your repository with me?

**Comment by heychazza** [comment]
> Again, unfortunately can't reproduce. Adding `vue` and `alpine` to `.env` seem to work as expected for me. Can you share your repository with me?

Do you have both packages with TUI?

**Comment by GregBrimble** [comment]
Yup.

**Comment by heychazza** [comment]
> Yup.

Provided you access!

**Comment by heychazza** [comment]
> Yup.

https://github.com/track/tailwindui.com/invitations

**Comment by GregBrimble** [comment]
I have no idea why, but:

```diff
- LANGUAGES=alpine,html,react,vue # defaults to html
- BUILDINDEX=1  # generate index file to view components offline
+ LANGUAGES=html,react,alpine,vue
+ BUILDINDEX=1
```

Fixed it.

That's gotta be something from the crawler itself, rather than my Action.

**Comment by GregBrimble** [comment]
Yeah, just locally tested an `.env` which looks like this, and it only pulled Alpine, HTML & React:

```ini
EMAIL=my@email.address
PASSWORD=Sup3r5ecr3tP@ssw0rd!
LANGUAGES=alpine,html,react,vue # defaults to html
BUILDINDEX=1  # generate index file to view components offline
```

Something about the way the crawler parses the `.env` files, @kiliman ?

**Comment by heychazza** [comment]
> Yeah, just locally tested an `.env` which looks like this, and it only pulled Alpine, HTML & React:
> 
> ```ini
> EMAIL=my@email.address
> PASSWORD=Sup3r5ecr3tP@ssw0rd!
> LANGUAGES=alpine,html,react,vue # defaults to html
> BUILDINDEX=1  # generate index file to view components offline
> ```
> 
> Something about the way the crawler parses the `.env` files, @kiliman ?

Yeah, seems to only get the first 3 from what it seems..

**Comment by heychazza** [comment]
https://github.com/motdotla/dotenv/issues/348#issuecomment-454632909

Seems to be an issue currently.. (inline wise)

**Comment by kiliman** [comment]
Wow, thanks for troubleshooting that.

Yeah, I noticed that inline comments weren't supported in `.env` files when I was testing. I just thought it was common knowledge, and that I was making a dumb assumption. The comments in the examples were more for documentation.

I will update the README to move the comments to a separate line, and also will make note of it in the docs.

Thanks again and I'm glad you're enjoying the tool.

BTW: Those React/Vue components are sweet. Tailwind Labs are on 🔥

**Comment by heychazza** [comment]
> Wow, thanks for troubleshooting that.
> 
> Yeah, I noticed that inline comments weren't supported in `.env` files when I was testing. I just thought it was common knowledge, and that I was making a dumb assumption. The comments in the examples were more for documentation.
> 
> I will update the README to move the comments to a separate line, and also will make note of it in the docs.
> 
> Thanks again and I'm glad you're enjoying the tool.
> 
> BTW: Those React/Vue components are sweet. Tailwind Labs are on 🔥

Haha, tbh mate - I fell for it as well and kept the inline comments (I didn't know! aha). I defo think just moving comments is all thats needed, as I just copy pasted it.

I agree, they are doing so fantastic now, pushing lots of great content all round 👍  Off topic, @adamwathan @steveschoger fantastic work guys (and the team!).

**Comment by ademers** [comment]
I can confirm that removing the inline comments from the `.env` worked in my existing, and brand new repos.

```js
EMAIL=******
PASSWORD=******
OUTPUT=$HOME/Projects/oss/tailwindui
LANGUAGES=alpine,html,react,vue
BUILDINDEX=1
```

Outputs

![CleanShot 2021-04-16 at 10 02 16](https://user-images.githubusercontent.com/901095/115035734-df185c80-9e9a-11eb-9e21-ac076c192fd7.png)

**Comment by heychazza** [comment]
Hey both, only odd thing I find is..

```
# OUTPUT optional, defaults to ./output
OUTPUT=/path/to/output
```

If I don't specify this, it outputs the same as the above? Is this a bug that it isn't outputting into the `output` folder?

**Comment by kiliman** [comment]
Hmm.. the code looks like this:
```javascript
const output = process.env.OUTPUT || './output'
```
If you don't provide `OUTPUT` then it should create a folder called *output* in your current directory, and store everything there: */output/html, /output/react, ...*

So what are you seeing?

In my GitHub Action, I set `OUTPUT=.` because I want it to output into the root of the project.

**Comment by heychazza** [comment]
> Hmm.. the code looks like this:
> 
> ```js
> const output = process.env.OUTPUT || './output'
> ```
> 
> If you don't provide `OUTPUT` then it should create a folder called _output_ in your current directory, and store everything there: _/output/html, /output/react, ..._
> 
> So what are you seeing?
> 
> In my GitHub Action, I set `OUTPUT=.` because I want it to output into the root of the project.

So, my **.env** is:
```
  
# LANGUAGES defaults to html
LANGUAGES=html,react,vue,alpine
# BUILDINDEX generate index file to view components offline
BUILDINDEX=1
```

![image](https://user-images.githubusercontent.com/47271716/115039443-5e705500-9ec8-11eb-858a-9008362a3eb9.png)

It shows as separate folders weirdly.

---

A github action bug as well, it's using "root" with no avatar as the author, shouldn't it be my github account?

**Comment by kiliman** [comment]
Not sure why it's not creating a top-level *output* folder.

But yes, v3 now creates separate directory trees for each language.

As for the commit user, it's working for me as *kiliman*. I even modified the commit message.

![image](https://user-images.githubusercontent.com/47168/115040896-e9892500-9e9f-11eb-9efb-b36a2960b090.png)

Look at the documentation for the action. You can specify the *actor* name (the commit user) although for me it defaulted to my username.

https://github.com/gregbrimble/tailwindui-crawler-action

### my default.yml file
```yml
name: Update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run crawler
        uses: gregbrimble/tailwindui-crawler-action@v1.1.0
        with:
          email: ${{ secrets.TAILWINDUI_EMAIL }}
          password: ${{ secrets.TAILWINDUI_PASSWORD }}
          commitmessage: 🤖 Update Tailwind UI components from Action
```

### v3 output directory structure
```
.
├── alpine
│   └── components
│       ├── application-ui
│       │   ├── application-shells
│       │   │   ├── multi-column
│       │   │   │   ├── constrained_three_column.html
│       │   │   │   ├── full_width_with_narrow_sidebar.html
│       │   │   │   └── full_width_with_narrow_sidebar_and_secondary_column_on_right.html
├── html
│   └── components
│       ├── application-ui
├── preview
│   ├── components
│   │   ├── application-ui
│   │   │   ├── application-shells
│   │   │   │   ├── multi-column
│   │   │   │   │   └── index.html
│   │   │   │   ├── sidebar
│   │   │   │   │   └── index.html
│   │   │   │   └── stacked
│   │   │   │       └── index.html
├── react
│   └── components
│       ├── application-ui
│       │   ├── application-shells
└── vue
    └── components
        ├── application-ui
        │   ├── application-shells
        │   │   ├── multi-column
        │   │   │   ├── constrained_three_column.vue
```
