### ISSUE TITLE
Directories with GH Actions are not generated correctly.

### ISSUE THREAD

**Issue by frbuceta** [kiliman/tailwindui-crawler#88]
The directories are being generated with the TailwindCSS URL.

![github com_tailwindui-components](https://github.com/user-attachments/assets/13e2d1e8-6035-4c56-a7ea-6c33ad1583fc)

```
name: Crawler
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1' # At 03:00 on Monday

jobs:   
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: kiliman/tailwindui-crawler-action@v1.3.1
        with:
          email: ${{ secrets.TAILWINDUI_EMAIL }}
          password: ${{ secrets.TAILWINDUI_PASS }}
          commitmessage: Update components
          current_branch: main
          branch: main
```
